export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_EMPS_SUCCESS = 'LOAD_EMPS_SUCCESS';
export const UPDATE_EMP_SUCCESS = 'UPDATE_EMP_SUCCESS';
export const CREATE_EMP_SUCCESS = 'CREATE_EMP_SUCCESS';
export const DELETE_EMP_SUCCESS = 'DELETE_EMP_SUCCESS';